In [3]:
# Define the documents as a dictionary where keys are document titles and values are document content
documents = {
    "Article: Pandas Basics": "This article covers the basics of using Pandas in Python.",
    "Tutorial: Data Visualization": "Learn about data visualization techniques with Python libraries.",
    "Case Study: Sales Analysis": "Analyze sales data using Python for a real-world case study."
}

In [4]:
# get the keys of the documents and store it in the list
key_documents = [key for key in documents]
# or we can use this
# key_documents = list(documents.keys())

# display the list of the key documents
print(key_documents)

['Article: Pandas Basics', 'Tutorial: Data Visualization', 'Case Study: Sales Analysis']


In [5]:
# Extract the category of the key documents and store it 
categories = [title.split(': ')[0] for title in documents]

# we can use this instead to better understanding
# categories = []
# for key_doc in documents:
#     category = key_doc.split(': ')[0]
#     categories.append(category)

# Print the list of categories
print(categories)

['Article', 'Tutorial', 'Case Study']


In [6]:

# Extract the content values and put them in a list
document_content_list = list(documents.values())

# Display the list of document content
print(document_content_list)

['This article covers the basics of using Pandas in Python.', 'Learn about data visualization techniques with Python libraries.', 'Analyze sales data using Python for a real-world case study.']


In [7]:
# Gather the set of all unique terms from the list content of document and diplay the result
# unique_terms = {term for doc in document_content_list for term in doc.split()}
# unique_terms

# this below code is easily for normal loop
# Initialize an empty set to store unique terms
unique_terms = set()

# Iterate through each document in document_content_list
for doc in document_content_list:
    # Split each document into terms and add them to the unique_terms set
    terms = doc.split()
    for term in terms:
        unique_terms.add(term)
unique_terms

{'Analyze',
 'Learn',
 'Pandas',
 'Python',
 'Python.',
 'This',
 'a',
 'about',
 'article',
 'basics',
 'case',
 'covers',
 'data',
 'for',
 'in',
 'libraries.',
 'of',
 'real-world',
 'sales',
 'study.',
 'techniques',
 'the',
 'using',
 'visualization',
 'with'}

In [32]:
# create a matrix for the document by using the unique term

doc_term_matrix = {}


# your code here
for term in unique_terms:
    doc_term_matrix[term] = []
    
    for doc in document_content_list:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)
            
# display the result of the matrix
doc_term_matrix

{'This': [1, 0, 0],
 'libraries.': [0, 1, 0],
 'visualization': [0, 1, 0],
 'covers': [1, 0, 0],
 'Python': [1, 1, 1],
 'in': [1, 0, 1],
 'the': [1, 0, 0],
 'data': [0, 1, 1],
 'with': [0, 1, 0],
 'sales': [0, 0, 1],
 'Learn': [0, 1, 0],
 'study.': [0, 0, 1],
 'about': [0, 1, 0],
 'techniques': [0, 1, 0],
 'real-world': [0, 0, 1],
 'a': [1, 1, 1],
 'article': [1, 0, 0],
 'using': [1, 0, 1],
 'of': [1, 0, 0],
 'Pandas': [1, 0, 0],
 'Python.': [1, 0, 0],
 'Analyze': [0, 0, 1],
 'basics': [1, 0, 0],
 'case': [0, 0, 1],
 'for': [0, 0, 1]}

In [10]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2

print(v3)

# display the content document from the result
[doc for doc in v3 * docs_array if doc]

[1 0 0]
[1 1 1]
-------
[1 0 0]


['This article covers the basics of using Pandas in Python.']

In [13]:
# find the document for those have at least one word
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 | v2

print(v3)

# display the content document from the result
    [doc for doc in v3 * docs_array if doc]

[1 0 0]
[1 1 1]
-------
[1 1 1]


['This article covers the basics of using Pandas in Python.',
 'Learn about data visualization techniques with Python libraries.',
 'Analyze sales data using Python for a real-world case study.']

In [40]:
# terms = [1,2,3,4,5,6,7,8,9]
# for term in terms:
#     print(term)
n = 10

for i in range(1, n, 3):
    print(i)

1
4
7


In [77]:
import pandas as pd

df = pd.read_csv('F:\\CADT\\Data Science\\TERM6\\Information Retrieval\\tdoc.csv', header = None, names = ["document", "content"])
df.columns
# left_aligned_df = df.style.set_properties(**{'text-align': 'left'})
# display(left_aligned_df)
pd.options.display.colheader_justify = 'center'
print(df.to_string())

    document                             content                           
0  Document 1           This is the first document. It contains some words.
1  Document 2  The second document is a bit longer and has different words.
2  Document 3  The third document is short. Short documents can be concise.


In [85]:
import pandas as pd
from tabulate import tabulate

# Read the CSV file into a DataFrame
df = pd.read_csv('F:\\CADT\\Data Science\\TERM6\\Information Retrieval\\tdoc.csv', header=None, names=["document", "content"])

# Define a function to format the DataFrame
def format_dataframe(df):
    # Set header alignment to center
    pd.options.display.colheader_justify = 'center'

    # Convert the DataFrame to a tabulated format with borders and text color
    formatted_table = tabulate(df, headers='keys', tablefmt='grid', showindex=False, numalign='center', stralign='center')

    return formatted_table

# Format and print the DataFrame
formatted_df = format_dataframe(df)
print(formatted_df)


+------------+--------------------------------------------------------------+
|  document  |                           content                            |
+============+==============================================================+
| Document 1 |     This is the first document. It contains some words.      |
+------------+--------------------------------------------------------------+
| Document 2 | The second document is a bit longer and has different words. |
+------------+--------------------------------------------------------------+
| Document 3 | The third document is short. Short documents can be concise. |
+------------+--------------------------------------------------------------+


In [20]:
# Homework save the unique_term to csv file 
import pandas as pd
# df = pd.DataFrame(unique_terms)
df = pd.DataFrame({'unique_term': list(unique_terms)})
df.to_csv('F:\\CADT\\Data Science\\TERM6\\Information Retrieval\\tdoc2.csv', index = False)

In [22]:
import pandas as pd
df = pd.read_csv('F:\\CADT\\Data Science\\TERM6\\Information Retrieval\\tdoc2.csv')
df

unique_term
0          covers
1      libraries.
2             the
3          study.
4            data
5         article
6           using
7           sales
8          basics
9            case
10          Learn
11           This
12         Python
13  visualization
14             of
15              a
16             in
17     real-world
18           with
19         Pandas
20        Analyze
21          about
22     techniques
23            for
24        Python.